[phases.setup]
nixPkgs = ["python310", "nodejs-18_x"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "npm install",
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "gunicorn api.index:app --bind 0.0.0.0:$PORT"