[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && npm install && npm run build"

[deploy]
startCommand = "gunicorn api.index:app --bind 0.0.0.0:$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10